"use client";
import { Web3Provider } from "context/web3";
import "styles/global.css";

import "@rainbow-me/rainbowkit/styles.css";

import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { hardhat, goerli } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";

const { chains, publicClient } = configureChains(
  [hardhat, goerli],
  [
    //alchemyProvider({ apiKey: process.env.ALCHEMY_ID }),
    publicProvider(),
  ]
);

const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  projectId: "dd7425657f4fc28fd70a178c2a6ee85c",
  chains,
});

const wagmiConfig = createConfig({
  //
  autoConnect: false,
  connectors,
  publicClient,
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chains}>
            <Web3Provider>{children}</Web3Provider>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
